name: KittyBlock
version: '${project.version}'
main: com.kittyscan.kittyblockspigot.KittyBlockSpigot
depend:
  - ProtocolLib
author: Lilly Schramm

description: Obfuscates the server query data towards known server scanners.

load: STARTUP
database: false
api-version: "1.12"

folia-supported: true

website: https://kittyscan.com